/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Interfaz.Solicitudes.miscuentas;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import tablas.TablaMisIncidentes;

/**
 *
 * @author GEUZ99
 */
public class Asegurados_MisSeguros extends javax.swing.JDialog {

    
    
    /**
     * Creates new form Asegurados_MisSeguros
     */
    Date miFecha = new Date();
    
    public Asegurados_MisSeguros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechatexto = formato.format(miFecha);
        Fecha.setText("Fecha Sistema " + fechatexto);
        String nombre = InsertarDatosNombre(Principal.loginSi);
        String telefono = InsertarDatosTelefono(Principal.loginSi);
        PrecioPrima.setText(InsertarPrecioPrima(Principal.loginSi));
        PrecioDeducible.setText(InsertarPrecioDeducible(Principal.loginSi));
        MontoAsegurado.setText(InsertarMontoAsegurado(Principal.loginSi));
        Estado.setText(InsertarEstado(Principal.loginSi));
        Datos(nombre, telefono, Principal.loginSi);

    }

    public void Datos(String nombre, String telefono, String dpi) {
        DatosArea.setText("Nombre: " + nombre + "\n" + "Telefono: " + telefono + "\n" + "DPI: " + dpi
                + "\n" + "Tipo: Asegurado");
    }

    public String InsertarDatosNombre(String dpi) {
        String nombre = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i].getDpi().equals(dpi)) {
                nombre = miscuentas[i].getNombre();
                return nombre;
            }
        }
        return nombre;
    }

    public String InsertarDatosTelefono(String dpi) {
        String telefono = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i].getDpi().equals(dpi)) {
                telefono = miscuentas[i].getTalefono();
                return telefono;
            }
        }
        return telefono;
    }

    public String InsertarPrecioPrima(String dpi) {
        String prima = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i] != null) {
                if (miscuentas[i].getDpi().equals(dpi)) {
                    prima = miscuentas[i].getPoliza();
                    return prima;
                }
            }
        }
        return prima;
    }

    public String InsertarPrecioDeducible(String dpi) {
        String deducible = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i] != null) {
                if (miscuentas[i].getDpi().equals(dpi)) {
                    deducible = miscuentas[i].getDeducible();
                    return deducible;
                }
            }
        }
        return deducible;
    }

    public String InsertarMontoAsegurado(String dpi) {
        String monto = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i] != null) {
                if (miscuentas[i].getDpi().equals(dpi)) {
                    monto = miscuentas[i].getMonto();
                    return monto;
                }
            }
        }
        return monto;
    }

    public String InsertarEstado(String dpi) {
        String estado = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i] != null) {
                if (miscuentas[i].getDpi().equals(dpi)) {
                    estado = "VULNERABLE";
                    return estado;
                }
            }
        }
        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DatosArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        PrecioPrima = new javax.swing.JLabel();
        PrecioDeducible = new javax.swing.JLabel();
        MontoAsegurado = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        btnRenovar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MIS SEGUROS");

        DatosArea.setColumns(20);
        DatosArea.setRows(5);
        jScrollPane1.setViewportView(DatosArea);

        jLabel1.setText("PRECIO PRIMA/POLIZA ");

        jLabel2.setText("PRECIO DEDUCIBLE");

        jLabel3.setText("MONTO ASEGURADO");

        jLabel4.setText("ESTADO");

        Fecha.setText("FECHA SISTEMA");

        PrecioPrima.setText("monto");

        PrecioDeducible.setText("monto");

        MontoAsegurado.setText("monto");

        Estado.setText("monto");

        btnRenovar.setBackground(new java.awt.Color(51, 255, 204));
        btnRenovar.setText("RENOVAR");
        btnRenovar.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PrecioPrima)
                                            .addComponent(MontoAsegurado))
                                        .addGap(149, 149, 149)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Estado)
                                            .addComponent(PrecioDeducible))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                        .addComponent(btnRenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fecha)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioPrima)
                            .addComponent(PrecioDeducible))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MontoAsegurado)
                            .addComponent(Estado)
                            .addComponent(btnRenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asegurados_MisSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asegurados_MisSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asegurados_MisSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asegurados_MisSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Asegurados_MisSeguros dialog = new Asegurados_MisSeguros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DatosArea;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel MontoAsegurado;
    private javax.swing.JLabel PrecioDeducible;
    private javax.swing.JLabel PrecioPrima;
    private javax.swing.JButton btnRenovar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
