/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Linea;
import Clases.Marca;
import Clases.Mecanica;
import Clases.Modelo;
import Clases.Repuesto;
import Clases.Tipo;
import Clases.Uso;

/**
 *
 * @author GEUZ99
 */
public class CargarDatos extends javax.swing.JDialog {

    /**
     * Creates new form CargarDatos
     */
    public CargarDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnCargar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CARGAR DATOS");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnCargar.setBackground(new java.awt.Color(51, 255, 204));
        btnCargar.setText("Cargar");
        btnCargar.setBorder(new javax.swing.border.MatteBorder(null));
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 255, 204));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.MatteBorder(null));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public static Tipo[] InvTipo = new Tipo[20];
    public static Modelo[] InvModelo = new Modelo[20]; 
    public static Marca[] InvMarca = new Marca[20];
    public static Linea[] InvLinea = new Linea[20];
    public static Uso[] InvUso = new Uso[20];
    public static Mecanica[] InvMecanica = new Mecanica[20];
    public static Repuesto[] InvRepuesto = new Repuesto[20];
    
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // BOTON DE CARGAR
        String infoCargas = txtArea.getText();
        String[] datos = infoCargas.split("\n"); // PRIMER SPLIT PARA SEPARA ENTRE LINEA
        for (String dato : datos) {            
            String[] infoText = dato.split(","); // SEGUNDO SPLIT PARA SEPARAR ENTRE COMAS            
            switch (infoText[0]) {
                case "TIPO":
                    //AGREGARLO AL ARREGLO DE TIPO
                    addTipo(new Tipo(infoText[1], infoText[2]));                    
                    break;
                case "MODELO":
                    //AGREGARLO AL ARREGLO DE MODELOS
                    addModelo(new Modelo(infoText[1], infoText[2])); 
                    break;
                case "MARCA":
                    //AGREGARLO AL ARREGLO DE MARCAS
                    addMarca(new Marca(infoText[1], infoText[2])); 
                    break;
                case "LINEA":
                   //AGREGARLO AL ARREGLO DE LINEA
                    addLinea(new Linea(infoText[1], infoText[2])); 
                    break;
                case "USO":
                    //AGREGARLO AL ARREGLO DE USO
                    addUso(new Uso(infoText[1], infoText[2])); 
                    break;
                case "MECANICA":
                    //AGREGARLO AL ARREGLO DE SERVICIOS
                    addMecanica(new Mecanica(infoText[1], infoText[2]));                
                    break;
                case "REPUESTO":
                    //AGREGARLO AL ARREGLO DE REPUESTOS
                    addRepuesto(new Repuesto(infoText[1], infoText[2]));  
                    break;
            }
        }
        PrintTipo();
        PrintModelo();
        PrintMarca();
        PrintLinea();
        PrintUso();
        PrintMecanica();
        PrintRepuesto();        
    }//GEN-LAST:event_btnCargarActionPerformed
            // "ADD" METODOS QUE AGREGAN PRIMERO AL ARREGLO DE LA CLASE
            // "PRINT" METODO QUE IMPRIME EL ARREGLO
    public void addTipo(Tipo obj) {
        for (int i = 0; i < 20; i++) {
            if (InvTipo[i] == null) {
                InvTipo[i] = obj;
                return;
            }
        }
    }
    public void PrintTipo() {
        for (int i = 0; i < 20; i++) {
            if (InvTipo[i] != null) {
                InvTipo[i].imprimir();
            }
        }
    }
    
    public void addModelo(Modelo obj) {
        for (int i = 0; i < 20; i++) {
            if (InvModelo[i] == null) {
                InvModelo[i] = obj;
                return;
            }
        }
    }
    public void PrintModelo() {
        for (int i = 0; i < 20; i++) {
            if (InvModelo[i] != null) {
                InvModelo[i].imprimir();
            }
        }
    } 
    public void addMarca(Marca obj) {
        for (int i = 0; i < 20; i++) {
            if (InvMarca[i] == null) {
                InvMarca[i] = obj;
                return;
            }
        }
    }
    public void PrintMarca() {
        for (int i = 0; i < 20; i++) {
            if (InvMarca[i] != null) {
                InvMarca[i].imprimir();
            }
        }
    } 
    public void addLinea(Linea obj) {
        for (int i = 0; i < 20; i++) {
            if (InvLinea[i] == null) {
                InvLinea[i] = obj;
                return;
            }
        }
    }
    public void PrintLinea() {
        for (int i = 0; i < 20; i++) {
            if (InvLinea[i] != null) {
                InvLinea[i].imprimir();
            }
        }
    } 
    public void addUso(Uso obj) {
        for (int i = 0; i < 20; i++) {
            if (InvUso[i] == null) {
                InvUso[i] = obj;
                return;
            }
        }
    }
    public void PrintUso() {
        for (int i = 0; i < 20; i++) {
            if (InvUso[i] != null) {
                InvUso[i].imprimir();
            }
        }
    } 
     public void addMecanica(Mecanica obj) {
        for (int i = 0; i < 20; i++) {
            if (InvMecanica[i] == null) {
                InvMecanica[i] = obj;
                return;
            }
        }
    }
    public void PrintMecanica() {
        for (int i = 0; i < 20; i++) {
            if (InvMecanica[i] != null) {
                InvMecanica[i].imprimir();
            }
        }
    } 
    public void addRepuesto(Repuesto obj) {
        for (int i = 0; i < 20; i++) {
            if (InvRepuesto[i] == null) {
                InvRepuesto[i] = obj;
                return;
            }
        }
    }
    public void PrintRepuesto() {
        for (int i = 0; i < 20; i++) {
            if (InvRepuesto[i] != null) {
                InvRepuesto[i].imprimir();
            }
        }
    } 
    
   
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // METODO CANCELAR
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CargarDatos dialog = new CargarDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
