/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Interfaz.Solicitudes.miscuentas;
import javax.swing.JTable;
import tablas.TablaMisIncidentes;

/**
 *
 * @author GEUZ99
 */
public class MisIncidentes extends javax.swing.JDialog {

    /**
     * Creates new form MisIncidentes
     */
    
    private JTable tablita;
    TablaMisIncidentes modelo;
    public MisIncidentes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tablita = new JTable();
        modelo = new TablaMisIncidentes(ReporteIncidente.incidentes);
        tablita.setModel(modelo);
        jScrollPane3.setViewportView(tablita);
        String nombre = InsertarDatosNombre(Principal.loginSi);
        String telefono = InsertarDatosTelefono(Principal.loginSi);
        PrecioPrima.setText(InsertarPrecioPrima(Principal.loginSi));
        PrecioDeducible.setText(InsertarPrecioDeducible(Principal.loginSi));
        Datos(nombre, telefono, Principal.loginSi);
    }
    public void Datos(String nombre, String telefono, String dpi) {
        DatosArea.setText("Nombre: " + nombre + "\n" + "Telefono: " + telefono + "\n" + "DPI: " + dpi
                + "\n" + "Tipo: Asegurado");
    }
     public String InsertarDatosNombre(String dpi) {
        String nombre = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i].getDpi().equals(dpi)) {
                nombre = miscuentas[i].getNombre();
                return nombre;
            }
        }
        return nombre;
    }
     public String InsertarDatosTelefono(String dpi) {
        String telefono = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i].getDpi().equals(dpi)) {
                telefono = miscuentas[i].getTalefono();
                return telefono;
            }
        }
        return telefono;
    }
      public String InsertarPrecioPrima(String dpi) {
        String prima = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i] != null) {
                if (miscuentas[i].getDpi().equals(dpi)) {
                    prima = miscuentas[i].getPoliza();
                    return prima;
                }
            }
        }
        return prima;
    }
     public String InsertarPrecioDeducible(String dpi) {
        String deducible = "";
        for (int i = 0; i < 20; i++) {
            if (miscuentas[i] != null) {
                if (miscuentas[i].getDpi().equals(dpi)) {
                    deducible = miscuentas[i].getDeducible();
                    return deducible;
                }
            }
        }
        return deducible;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DatosArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PrecioPrima = new javax.swing.JLabel();
        PrecioDeducible = new javax.swing.JLabel();
        btnDetalle = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MIS INCIDENTES");

        DatosArea.setColumns(20);
        DatosArea.setRows(5);
        jScrollPane1.setViewportView(DatosArea);

        jLabel1.setText("PRECIO PRIMA");

        jLabel2.setText("PRECIO DEDUCIBLE");

        PrecioPrima.setText("monto");

        PrecioDeducible.setText("monto");

        btnDetalle.setBackground(new java.awt.Color(51, 255, 204));
        btnDetalle.setText("DETALLE");
        btnDetalle.setBorder(new javax.swing.border.MatteBorder(null));

        btnPagar.setBackground(new java.awt.Color(51, 255, 204));
        btnPagar.setText("PAGAR");
        btnPagar.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PrecioPrima)
                                .addGap(194, 194, 194)
                                .addComponent(PrecioDeducible)))
                        .addGap(0, 345, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioPrima)
                    .addComponent(PrecioDeducible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MisIncidentes dialog = new MisIncidentes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DatosArea;
    private javax.swing.JLabel PrecioDeducible;
    private javax.swing.JLabel PrecioPrima;
    private javax.swing.JButton btnDetalle;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
